### ISSUE TITLE
FileNotFoundError solved

### ISSUE THREAD

**Issue by mike123404** [zuramai/Auto-Post-Instagram-Photo#4]
$ python run.py      
Traceback (most recent call last):
  File "/home/kali/Auto-Post-Instagram-Photo/run.py", line 11, in <module>
    subprocess.call("php upload.php")
  File "/usr/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php upload.php

**Comment by mike123404** [comment]
i solved that problem with changing line 11 to: subprocess.call(["php", "/home/kali/Auto-Post-Instagram-Photo/upload.php"])
