### ISSUE TITLE
Fatal error line 69 solved 

### ISSUE THREAD

**Issue by mike123404** [zuramai/Auto-Post-Instagram-Photo#5]
$ python run.py
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/kali/Auto-Post-Instagram-Photo/instagram-photo-video-upload-api.class.php:69
Stack trace:
#0 /home/kali/Auto-Post-Instagram-Photo/instagram-photo-video-upload-api.class.php(46): InstagramUpload->GetToken()
#1 /home/kali/Auto-Post-Instagram-Photo/upload.php(17): InstagramUpload->Login()
#2 {main}
  thrown in /home/kali/Auto-Post-Instagram-Photo/instagram-photo-video-upload-api.class.php on line 69
Uploaded! wait for 10 sec

IT DIDNT UPLOAD THE PHOTO

**Comment by mike123404** [comment]
solution:
sudo apt-get install php-curl
